// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaGestionConstructora.Data;

#nullable disable

namespace SistemaGestionConstructora.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241217012406_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SistemaGestionConstructora.Models.Asignacion", b =>
                {
                    b.Property<int>("IDAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("IDEmpleado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDProyecto")
                        .HasColumnType("INTEGER");

                    b.HasKey("IDAsignacion");

                    b.ToTable("Asignaciones");
                });

            modelBuilder.Entity("SistemaGestionConstructora.Models.Empleado", b =>
                {
                    b.Property<int>("IDEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoriaLaboral")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Salario")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("IDEmpleado");

                    b.HasIndex("CorreoElectronico")
                        .IsUnique();

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("SistemaGestionConstructora.Models.Proyecto", b =>
                {
                    b.Property<int>("IDProyecto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreDescriptivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("IDProyecto");

                    b.ToTable("Proyectos");
                });
#pragma warning restore 612, 618
        }
    }
}
